/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7f3cb15a-d95b-4c85-bfdd-fb24e7aa8515",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4tZP0FK1D",
    "aws_user_pools_web_client_id": "q6tq45b5f91o17c8ti8onpob4",
    "oauth": {}
};


export default awsmobile;
