/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7f3cb15a-d95b-4c85-bfdd-fb24e7aa8515",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4tZP0FK1D",
    "aws_user_pools_web_client_id": "q6tq45b5f91o17c8ti8onpob4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fxsjp52p5ffo5bbfd5xwfcgqoe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kq2ldh4r5ncnpadpx53lwure3i"
};


export default awsmobile;
